# Generated by Django 5.1.6 on 2025-03-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_beat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='tages',
        ),
    ]
