# Generated by Django 5.1.6 on 2025-03-07 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_beat', '0002_remove_song_tages'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='tages',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
