# Generated by Django 5.1.6 on 2025-03-07 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_beat', '0003_song_tages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='tages',
            new_name='tags',
        ),
    ]
