# Generated by Django 5.1.6 on 2025-03-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_beat', '0004_rename_tages_song_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='singer',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
